name: Fill Temp

on:
  schedule:
    - cron: '0 0 * * *'  # 台灣時間早上 8:00
  workflow_dispatch:      # 允許手動測試

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run script
        env:
          EMP_ID: ${{ secrets.EMP_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python fill_temp.py
